platform :ios, ‘9.0’

xcodeproj ‘Doorbell’  

pod 'AFNetworking', '~> 2.0'

pod 'EstimoteSDK'
pod 'Parse', '~> 1.4'
pod "FBSDKCoreKit"
pod "FBSDKLoginKit"
pod "FBSDKShareKit"
pod "FBSDKMessengerShareKit"
pod 'ParseFacebookUtilsV4'
pod 'RKSwipeBetweenViewControllers'
pod 'DRCellSlideGestureRecognizer'
pod 'SVPullToRefresh'
pod 'CNPPopupController'
pod 'LRTextField'
pod 'FormatterKit'
pod 'SDWebImage', '~>3.7'
pod 'MLPAutoCompleteTextField', '~> 1.5'
pod 'TLYShyNavBar'
pod 'VCTransitionsLibrary'
pod 'JSQMessagesViewController'
pod 'MOOMaskedIconView', '~> 0.1'
pod 'MMPopupView'
pod 'JTSImageViewController', '~> 1.5'
pod 'LGSideMenuController', '~> 1.0.0'
pod 'Bohr'
pod 'SESlideTableViewCell'
pod 'UIColor+FlatColors'
pod 'JTHamburgerButton', '~> 1.0'
pod 'FTAssetRenderer'
pod 'UIImage-Resize', '~> 1.0'





