platform :ios, ‘9.0’

xcodeproj ‘Doorbell’  

pod 'AFNetworking', '~> 2.0'

pod 'EstimoteSDK'
pod 'Parse', '~> 1.4'
pod "FBSDKCoreKit"
pod "FBSDKLoginKit"
pod "FBSDKShareKit"
pod "FBSDKMessengerShareKit"
pod 'ParseFacebookUtilsV4'

pod 'RKSwipeBetweenViewControllers'
pod 'DRCellSlideGestureRecognizer'
pod 'SVPullToRefresh'
pod 'CNPPopupController'
pod 'LRTextField'
pod 'FormatterKit'
pod 'SDWebImage', '~>3.7'
pod 'MLPAutoCompleteTextField', '~> 1.5'
pod 'TLYShyNavBar'
pod 'VCTransitionsLibrary'


